language: rust
rust: nightly

matrix:
  fast_finish: true
  include:
    - name: "rustfmt/clippy"
      env: TARGET=i586-unknown-linux-gnu
      script: sh ci/tools.sh
    # Tier 1 targets:
    - name: "x86_64-unknown-linux-gnu"
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "x86_64-unknown-linux-gnu (beta)"
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "x86_64-unknown-linux-gnu (stable)"
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "x86_64-unknown-linux-gnu (Rust 1.32.0)"
      rust: 1.32.0
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "i686-unknown-linux-gnu"
      env: TARGET=i686-unknown-linux-gnu CROSS=1

install: travis_retry rustup target add "${TARGET}"
script: sh ci/run.sh
