reorder_imports = true
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
max_width = 120
comment_width = 120
edition = "2018"
imports_layout = "HorizontalVertical"
tab_spaces = 2
trailing_comma = "Never"

ignore = [
  ".git",
  ".vagrant",
  "benches",
  "examles",
  "hashbrown",
  "project",
  "target",
  "tests",
  "build.rs",
  "src/external",
  "src/raw",
  "src/entry.rs",
  "src/error.rs",
  "src/hasher.rs",
  "src/iterator.rs",
  "src/keys.rs",
  "src/lib.rs",
  "src/state.rs",
  "src/values.rs"
]
